version: '3.8'

services:
  bot:
    build: .
    container_name: serials-bot
    restart: unless-stopped
    ports:
      - "8443:8443"
    env_file:
      - .env
    volumes:
      - ./bot:/app/bot
    environment:
      - ENVIRONMENT=production
networks:
  serials-network:
    external: true