version: '3.8'

services:
  bot:
    build: .
    container_name: serials-bot
    restart: unless-stopped
    ports:
      - "8443:8443"
    env_file:
      - .env
    volumes:
      - ./bot:/app/bot
    environment:
      - ENVIRONMENT=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8443/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 